engine_start:
  description: Remote start your Toyota vehicle.
  fields:
    vehicle:
      description:
        Device (vehicle) you wish to start.
      required: true
      selector:
        device:
          integration: toyota_na
engine_stop:
  description: Remote stop your Toyota vehicle.
  fields:
    vehicle:
      description:
        Device (vehicle) you wish to stop.
      required: true
      selector:
        device:
          integration: toyota_na